language: node_js
node_js:
- node
- lts/*
cache:
directories:
- ~/.npm
before_script:
- npm install -g npm@latest
- npm install
script:
- npm ci
jobs:
include:
- stage: deploy
node_js: lts/*
branches:
only:
- master